common = '''Être Conjugation (To be)
Avoir Conjugation (To have)
Pouvoir Conjugation (Can, to be able to)
Vouloir Conjugation (To want)
Faire Conjugation (To do, to make)
Aller Conjugation (To go)
Venir Conjugation (To come)
Devenir Conjugation (To become)
Prendre Conjugation (To take)
Comprendre Conjugation (To understand)
Apprendre Conjugation (To learn)
Voir Conjugation (To see)
Devoir Conjugation (Must)
Recevoir Conjugation (To receive)
Croire Conjugation (To believe)
Boire Conjugation (To drink)
Acheter Conjugation (To buy)
Vivre Conjugation (To live)
Dire Conjugation (To say)
Lire Conjugation (To read)
Écrire Conjugation (To write)
Rire Conjugation (To laugh)
Sourire Conjugation (To smile)
Suivre Conjugation (To follow)
Savoir Conjugation (To know)
Connaître Conjugation (To know)
Naître Conjugation (To be born)
Mourir Conjugation (To die)
Dormir Conjugation (To sleep)
Ouvrir Conjugation (To open)
Couvrir Conjugation (To cover)
Découvrir Conjugation (To discover)
Mettre Conjugation (To put)
Permettre Conjugation (To allow)
Promettre Conjugation (To promise)
Manger Conjugation (To eat)
Partager Conjugation (To share)
Partir Conjugation (To leave)
Sortir Conjugation (To go out)
Tenir Conjugation (To hold)
Obtenir Conjugation (To get)
Produire Conjugation (To produce)
Détruire Conjugation (To destroy)
Traduire Conjugation (To translate)
Conduire Conjugation (To drive)
Cuire Conjugation (To cook)
Courir Conjugation (To run)
Appeler Conjugation (To call, to be called)
Intéresser Conjugation (To interest)
Inquiéter Conjugation (To worry)
Souvenir Conjugation (To remember)
Lever Conjugation (To get up)
Parler Conjugation (To speak)
Aimer Conjugation (To like, to love)
Donner Conjugation (To give)
Demander Conjugation (To ask)
Trouver Conjugation (To find)
Passer Conjugation (To pass)
Porter Conjugation (To wear)
Penser Conjugation (To think)
Écouter Conjugation (To listen)
Rester Conjugation (To stay)
Étudier Conjugation (To study)
Montrer Conjugation (To show)
Arriver Conjugation (To arrive)
Laisser Conjugation (To leave )
Payer Conjugation (To pay)
Jouer Conjugation (To play)
Changer Conjugation (To change)
Décider Conjugation (To decide)
Commencer Conjugation (To begin)
Compter Conjugation (To count)
Expliquer Conjugation (To explain)
Gagner Conjugation (To win)
Exister Conjugation (To exist)
Travailler Conjugation (To work)
Rencontrer Conjugation (To meet)
Chercher Conjugation (To search)
Entrer Conjugation (To enter)
Préparer Conjugation (To prepare)
Vendre Conjugation (To sell)
Attendre Conjugation (To wait)
Perdre Conjugation (To lose)
Entendre Conjugation (To hear)
Répondre Conjugation (To respond)
Rendre Conjugation (To return sth)
Prétendre Conjugation (To claim)
Défendre Conjugation (To defend)
Fondre Conjugation (To melt)
Descendre Conjugation (To descend)
Finir Conjugation (To finish)
Réussir Conjugation (To succeed)
Choisir Conjugation (To choose)
Agir Conjugation (To act)
Investir Conjugation (To invest)
Obéir Conjugation (To obey)
Grossir Conjugation (To gain weight)
Grandir Conjugation (To grow up)
Vieillir Conjugation (To grow old)
Réfléchir Conjugation (To think)'''

common = common.split('\n')
infs = [x.split(' ')[0] for x in common]
lowerinfs = [x.lower() for x in infs]
print(lowerinfs)